name: thegraux.com
favicon: null
layout_spectrum: 0.4741441127844155
typography_spectrum: 0.15732981800101697
title: The Graux
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#5f5f5f'
    - '#9f9f9f'
    - '#ff0000'
  brandStrength: 0.9375
  lightness: 0.875
  saturation: 0.25
  rhythmicContrast: 0.7895275233313441
purpose: []
