name: thegraux.com
favicon: null
layout_spectrum: 0.4741441127844155
typography_spectrum: 0.15732981800101697
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8061333373188972
  lightness: 0.307993225986138
  saturation: 0.005410982761532068
  rhythmicContrast: 0.7895275233313441
purpose: []
