name: thegraux.com
favicon: null
layout_spectrum: 0.93522
typography_spectrum: 1
title: The Graux
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#5f5f5f'
    - '#9f9f9f'
    - '#ff0000'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.4375
  rhythmicContrast: 1
purpose: []
